version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbox_app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    container_name: sandbox_db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
